<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Estate;

class EstateSeeder extends Seeder
{
    public function run()
    {
        // Test ilanları oluştur
        Estate::create([
            'type' => 'Villa',
            'status' => 'Satılık',
            'name' => 'Midyat Merkez Villa',
            'price' => 2500000,
            'main_image' => 'estates/main/M4SGVyRTdD7PGXiJELuGpPRRsx2JzuKIIp6OpwVW.png',
            'address' => 'Midyat Merkez, Mardin',
            'latitude' => 37.4192,
            'longitude' => 41.3391,
            'gross_m2' => 200,
            'net_m2' => 180,
            'number_of_rooms' => '4+1',
            'building_age' => 5,
            'number_of_floors' => 2,
            'heating' => 'Doğalgaz',
            'number_of_bathrooms' => 2,
            'kitchen' => 'Amerikan',
            'parking' => 'Kapalı Otopark',
            'furnished' => 'Evet',
            'usage_status' => 'Boş',
            'site_content' => 'Evet',
            'site_name' => 'Midyat Villa Sitesi',
            'help_tl' => 500,
            'available_for_credit' => 'Evet',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Sahibinden',
            'exchange' => 'Yok'
        ]);

        Estate::create([
            'type' => 'Daire',
            'status' => 'Kiralık',
            'name' => 'Merkez 3+1 Daire',
            'price' => 3500,
            'main_image' => 'estates/main/UDADAKOQXSSRENwJp7497BjrXLVd4jmUoMiBJeyF.png',
            'address' => 'Midyat Merkez, Mardin',
            'latitude' => 37.4195,
            'longitude' => 41.3395,
            'gross_m2' => 120,
            'net_m2' => 110,
            'number_of_rooms' => '3+1',
            'building_age' => 3,
            'number_of_floors' => 4,
            'heating' => 'Doğalgaz',
            'number_of_bathrooms' => 1,
            'kitchen' => 'Ayrı',
            'parking' => 'Açık Otopark',
            'furnished' => 'Hayır',
            'usage_status' => 'Boş',
            'site_content' => 'Hayır',
            'site_name' => null,
            'help_tl' => null,
            'available_for_credit' => 'Hayır',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Emlakçıdan',
            'exchange' => 'Yok'
        ]);

        Estate::create([
            'type' => 'Arsa',
            'status' => 'Satılık',
            'name' => 'Midyat Arsa',
            'price' => 500000,
            'main_image' => 'estates/main/f8APei0Ero4ExdFc2RGRRRKFwsbjLnJJlkae846f.png',
            'address' => 'Midyat Çevre Yolu, Mardin',
            'latitude' => 37.4200,
            'longitude' => 41.3400,
            'open_area_m2' => 500,
            'title_deed_status' => 'Arsa Tapulu',
            'from_person' => 'Sahibinden',
            'exchange' => 'Yok'
        ]);

        // Ek test ilanları
        Estate::create([
            'type' => 'Daire',
            'status' => 'Satılık',
            'name' => 'Bahçelievler 2+1 Daire',
            'price' => 850000,
            'main_image' => 'estates/main/M4SGVyRTdD7PGXiJELuGpPRRsx2JzuKIIp6OpwVW.png',
            'address' => 'Bahçelievler Mahallesi, Midyat',
            'latitude' => 37.4198,
            'longitude' => 41.3398,
            'gross_m2' => 85,
            'net_m2' => 75,
            'number_of_rooms' => '2+1',
            'building_age' => 8,
            'number_of_floors' => 5,
            'heating' => 'Kombi',
            'number_of_bathrooms' => 1,
            'kitchen' => 'Ayrı',
            'parking' => 'Yok',
            'furnished' => 'Hayır',
            'usage_status' => 'Boş',
            'site_content' => 'Hayır',
            'site_name' => null,
            'help_tl' => null,
            'available_for_credit' => 'Evet',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Emlakçıdan',
            'exchange' => 'Yok'
        ]);

        Estate::create([
            'type' => 'Müstakil',
            'status' => 'Kiralık',
            'name' => 'Gölcük Müstakil Ev',
            'price' => 2500,
            'main_image' => 'estates/main/UDADAKOQXSSRENwJp7497BjrXLVd4jmUoMiBJeyF.png',
            'address' => 'Gölcük Mahallesi, Midyat',
            'latitude' => 37.4202,
            'longitude' => 41.3402,
            'gross_m2' => 150,
            'net_m2' => 130,
            'number_of_rooms' => '3+1',
            'building_age' => 12,
            'number_of_floors' => 1,
            'heating' => 'Soba',
            'number_of_bathrooms' => 1,
            'kitchen' => 'Ayrı',
            'parking' => 'Açık Otopark',
            'furnished' => 'Evet',
            'usage_status' => 'Boş',
            'site_content' => 'Hayır',
            'site_name' => null,
            'help_tl' => null,
            'available_for_credit' => 'Hayır',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Sahibinden',
            'exchange' => 'Yok'
        ]);

        Estate::create([
            'type' => 'Dükkan',
            'status' => 'Satılık',
            'name' => 'Merkez Dükkan',
            'price' => 1200000,
            'main_image' => 'estates/main/f8APei0Ero4ExdFc2RGRRRKFwsbjLnJJlkae846f.png',
            'address' => 'Midyat Merkez, Mardin',
            'latitude' => 37.4190,
            'longitude' => 41.3390,
            'gross_m2' => 80,
            'net_m2' => 70,
            'number_of_rooms' => '1+0',
            'building_age' => 15,
            'number_of_floors' => 1,
            'heating' => 'Yok',
            'number_of_bathrooms' => 1,
            'kitchen' => 'Yok',
            'parking' => 'Yok',
            'furnished' => 'Hayır',
            'usage_status' => 'Boş',
            'site_content' => 'Hayır',
            'site_name' => null,
            'help_tl' => null,
            'available_for_credit' => 'Evet',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Sahibinden',
            'exchange' => 'Yok'
        ]);

        Estate::create([
            'type' => 'Ofis',
            'status' => 'Kiralık',
            'name' => 'Plaza Ofis',
            'price' => 4000,
            'main_image' => 'estates/main/M4SGVyRTdD7PGXiJELuGpPRRsx2JzuKIIp6OpwVW.png',
            'address' => 'Midyat Plaza, Mardin',
            'latitude' => 37.4193,
            'longitude' => 41.3393,
            'gross_m2' => 100,
            'net_m2' => 90,
            'number_of_rooms' => '2+0',
            'building_age' => 5,
            'number_of_floors' => 6,
            'heating' => 'Merkezi',
            'number_of_bathrooms' => 1,
            'kitchen' => 'Yok',
            'parking' => 'Kapalı Otopark',
            'furnished' => 'Evet',
            'usage_status' => 'Boş',
            'site_content' => 'Evet',
            'site_name' => 'Midyat Plaza',
            'help_tl' => 200,
            'available_for_credit' => 'Hayır',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Emlakçıdan',
            'exchange' => 'Yok'
        ]);

        Estate::create([
            'type' => 'Villa',
            'status' => 'Satılık',
            'name' => 'Lüks Villa',
            'price' => 3500000,
            'main_image' => 'estates/main/UDADAKOQXSSRENwJp7497BjrXLVd4jmUoMiBJeyF.png',
            'address' => 'Yenimahalle, Midyat',
            'latitude' => 37.4205,
            'longitude' => 41.3405,
            'gross_m2' => 250,
            'net_m2' => 220,
            'number_of_rooms' => '5+1',
            'building_age' => 2,
            'number_of_floors' => 2,
            'heating' => 'Doğalgaz',
            'number_of_bathrooms' => 3,
            'kitchen' => 'Amerikan',
            'parking' => 'Kapalı Otopark',
            'furnished' => 'Evet',
            'usage_status' => 'Boş',
            'site_content' => 'Evet',
            'site_name' => 'Lüks Villa Sitesi',
            'help_tl' => 800,
            'available_for_credit' => 'Evet',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Sahibinden',
            'exchange' => 'Yok'
        ]);

        Estate::create([
            'type' => 'Daire',
            'status' => 'Kiralık',
            'name' => 'Cumhuriyet 1+1 Daire',
            'price' => 2000,
            'main_image' => 'estates/main/f8APei0Ero4ExdFc2RGRRRKFwsbjLnJJlkae846f.png',
            'address' => 'Cumhuriyet Mahallesi, Midyat',
            'latitude' => 37.4196,
            'longitude' => 41.3396,
            'gross_m2' => 60,
            'net_m2' => 55,
            'number_of_rooms' => '1+1',
            'building_age' => 20,
            'number_of_floors' => 4,
            'heating' => 'Kombi',
            'number_of_bathrooms' => 1,
            'kitchen' => 'Ayrı',
            'parking' => 'Yok',
            'furnished' => 'Hayır',
            'usage_status' => 'Boş',
            'site_content' => 'Hayır',
            'site_name' => null,
            'help_tl' => null,
            'available_for_credit' => 'Hayır',
            'title_deed_status' => 'Kat Mülkiyetli',
            'from_person' => 'Emlakçıdan',
            'exchange' => 'Yok'
        ]);
    }
} 